# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trainergui.ui'
#
# Created: Fri Jun 17 09:26:18 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(321, 664)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 120, 301, 511))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.txtMinPulse = QtGui.QLineEdit(self.frame)
        self.txtMinPulse.setGeometry(QtCore.QRect(120, 250, 101, 27))
        self.txtMinPulse.setObjectName(_fromUtf8("txtMinPulse"))
        self.txtMaxSensor = QtGui.QLineEdit(self.frame)
        self.txtMaxSensor.setGeometry(QtCore.QRect(120, 280, 101, 27))
        self.txtMaxSensor.setObjectName(_fromUtf8("txtMaxSensor"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(30, 250, 81, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 91, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 310, 81, 21))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 81, 21))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.txtMaxPulse = QtGui.QLineEdit(self.frame)
        self.txtMaxPulse.setGeometry(QtCore.QRect(120, 220, 101, 27))
        self.txtMaxPulse.setObjectName(_fromUtf8("txtMaxPulse"))
        self.chkCalibrated = QtGui.QCheckBox(self.frame)
        self.chkCalibrated.setGeometry(QtCore.QRect(42, 340, 97, 22))
        self.chkCalibrated.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkCalibrated.setObjectName(_fromUtf8("chkCalibrated"))
        self.txtMaxGoal = QtGui.QLineEdit(self.frame)
        self.txtMaxGoal.setGeometry(QtCore.QRect(120, 160, 101, 27))
        self.txtMaxGoal.setObjectName(_fromUtf8("txtMaxGoal"))
        self.txtMinSensor = QtGui.QLineEdit(self.frame)
        self.txtMinSensor.setGeometry(QtCore.QRect(120, 310, 101, 27))
        self.txtMinSensor.setObjectName(_fromUtf8("txtMinSensor"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 190, 61, 21))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.cmbSmoothing = QtGui.QComboBox(self.frame)
        self.cmbSmoothing.setEnabled(True)
        self.cmbSmoothing.setGeometry(QtCore.QRect(122, 110, 101, 27))
        self.cmbSmoothing.setObjectName(_fromUtf8("cmbSmoothing"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setEnabled(False)
        self.label_8.setGeometry(QtCore.QRect(28, 80, 81, 21))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.txtMaxSpeed = QtGui.QLineEdit(self.frame)
        self.txtMaxSpeed.setEnabled(True)
        self.txtMaxSpeed.setGeometry(QtCore.QRect(122, 80, 101, 27))
        self.txtMaxSpeed.setReadOnly(True)
        self.txtMaxSpeed.setObjectName(_fromUtf8("txtMaxSpeed"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(30, 280, 81, 21))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setEnabled(False)
        self.label_14.setGeometry(QtCore.QRect(22, 110, 91, 21))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.txtMinGoal = QtGui.QLineEdit(self.frame)
        self.txtMinGoal.setGeometry(QtCore.QRect(120, 190, 101, 27))
        self.txtMinGoal.setObjectName(_fromUtf8("txtMinGoal"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 470, 81, 16))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.txtSpeed = QtGui.QLineEdit(self.frame)
        self.txtSpeed.setEnabled(True)
        self.txtSpeed.setGeometry(QtCore.QRect(140, 430, 81, 27))
        self.txtSpeed.setReadOnly(True)
        self.txtSpeed.setObjectName(_fromUtf8("txtSpeed"))
        self.chkPower = QtGui.QCheckBox(self.frame)
        self.chkPower.setEnabled(True)
        self.chkPower.setGeometry(QtCore.QRect(42, 410, 97, 22))
        self.chkPower.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkPower.setText(_fromUtf8(""))
        self.chkPower.setCheckable(False)
        self.chkPower.setObjectName(_fromUtf8("chkPower"))
        self.txtPosition = QtGui.QLineEdit(self.frame)
        self.txtPosition.setEnabled(True)
        self.txtPosition.setGeometry(QtCore.QRect(122, 380, 101, 27))
        self.txtPosition.setReadOnly(True)
        self.txtPosition.setObjectName(_fromUtf8("txtPosition"))
        self.txtSensorRaw = QtGui.QLineEdit(self.frame)
        self.txtSensorRaw.setEnabled(True)
        self.txtSensorRaw.setGeometry(QtCore.QRect(124, 470, 101, 27))
        self.txtSensorRaw.setReadOnly(True)
        self.txtSensorRaw.setObjectName(_fromUtf8("txtSensorRaw"))
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(52, 380, 61, 21))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(22, 410, 91, 17))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.chkEnabled = QtGui.QCheckBox(self.frame)
        self.chkEnabled.setGeometry(QtCore.QRect(42, 10, 97, 22))
        self.chkEnabled.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkEnabled.setObjectName(_fromUtf8("chkEnabled"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(52, 40, 61, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.txtGoal = QtGui.QLineEdit(self.frame)
        self.txtGoal.setGeometry(QtCore.QRect(122, 40, 101, 27))
        self.txtGoal.setObjectName(_fromUtf8("txtGoal"))
        self.chkMoving = QtGui.QCheckBox(self.frame)
        self.chkMoving.setEnabled(True)
        self.chkMoving.setGeometry(QtCore.QRect(42, 430, 97, 22))
        self.chkMoving.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkMoving.setText(_fromUtf8(""))
        self.chkMoving.setCheckable(False)
        self.chkMoving.setObjectName(_fromUtf8("chkMoving"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 430, 91, 17))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.sliderGoal = QtGui.QSlider(self.frame)
        self.sliderGoal.setGeometry(QtCore.QRect(260, 10, 31, 491))
        self.sliderGoal.setMaximum(990000)
        self.sliderGoal.setSingleStep(10000)
        self.sliderGoal.setPageStep(100000)
        self.sliderGoal.setOrientation(QtCore.Qt.Vertical)
        self.sliderGoal.setInvertedAppearance(False)
        self.sliderGoal.setInvertedControls(False)
        self.sliderGoal.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderGoal.setTickInterval(10000)
        self.sliderGoal.setObjectName(_fromUtf8("sliderGoal"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(-10, 50, 71, 21))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(-10, 80, 71, 21))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cmbBus = QtGui.QComboBox(self.centralwidget)
        self.cmbBus.setGeometry(QtCore.QRect(70, 50, 241, 27))
        self.cmbBus.setFrame(True)
        self.cmbBus.setObjectName(_fromUtf8("cmbBus"))
        self.cmbServo = QtGui.QComboBox(self.centralwidget)
        self.cmbServo.setGeometry(QtCore.QRect(70, 80, 241, 27))
        self.cmbServo.setObjectName(_fromUtf8("cmbServo"))
        self.chkEnableAll = QtGui.QCheckBox(self.centralwidget)
        self.chkEnableAll.setGeometry(QtCore.QRect(190, 10, 121, 22))
        self.chkEnableAll.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chkEnableAll.setObjectName(_fromUtf8("chkEnableAll"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.chkEnabled, self.txtGoal)
        MainWindow.setTabOrder(self.txtGoal, self.txtMaxSpeed)
        MainWindow.setTabOrder(self.txtMaxSpeed, self.cmbSmoothing)
        MainWindow.setTabOrder(self.cmbSmoothing, self.txtMinGoal)
        MainWindow.setTabOrder(self.txtMinGoal, self.txtMaxGoal)
        MainWindow.setTabOrder(self.txtMaxGoal, self.txtMinPulse)
        MainWindow.setTabOrder(self.txtMinPulse, self.txtMaxPulse)
        MainWindow.setTabOrder(self.txtMaxPulse, self.txtMinSensor)
        MainWindow.setTabOrder(self.txtMinSensor, self.txtMaxSensor)
        MainWindow.setTabOrder(self.txtMaxSensor, self.chkCalibrated)
        MainWindow.setTabOrder(self.chkCalibrated, self.txtPosition)
        MainWindow.setTabOrder(self.txtPosition, self.chkPower)
        MainWindow.setTabOrder(self.chkPower, self.chkMoving)
        MainWindow.setTabOrder(self.chkMoving, self.txtSpeed)
        MainWindow.setTabOrder(self.txtSpeed, self.txtSensorRaw)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "ROS Servo Trainer", None))
        self.label_3.setText(_translate("MainWindow", "Min Pulse", None))
        self.label_4.setText(_translate("MainWindow", "Max Pulse", None))
        self.label_5.setText(_translate("MainWindow", "MinSensor", None))
        self.label_2.setText(_translate("MainWindow", "Max Goal", None))
        self.chkCalibrated.setText(_translate("MainWindow", "Calibrated", None))
        self.label.setText(_translate("MainWindow", "Min Goal", None))
        self.label_8.setText(_translate("MainWindow", "MaxSpeed", None))
        self.label_6.setText(_translate("MainWindow", "Max Sensor", None))
        self.label_14.setText(_translate("MainWindow", "Smoothing", None))
        self.label_7.setText(_translate("MainWindow", "Sensor Raw", None))
        self.label_10.setText(_translate("MainWindow", "Position", None))
        self.label_11.setText(_translate("MainWindow", "Power", None))
        self.chkEnabled.setText(_translate("MainWindow", "Enabled", None))
        self.label_9.setText(_translate("MainWindow", "Goal", None))
        self.label_15.setText(_translate("MainWindow", "Moving", None))
        self.label_12.setText(_translate("MainWindow", "Bus", None))
        self.label_13.setText(_translate("MainWindow", "Servo", None))
        self.chkEnableAll.setText(_translate("MainWindow", "Enable All", None))

